# Generated by Django 5.1.7 on 2025-04-14 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=20)),
                ('business', models.CharField(max_length=255)),
                ('plan_fact', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('parent_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('show', models.BooleanField()),
                ('type', models.CharField(max_length=50)),
                ('operation', models.CharField(max_length=50)),
                ('reverse_sign', models.BooleanField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color_code', models.CharField(max_length=7)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
