# Generated by Django 5.1.7 on 2025-04-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_indicator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='reports',
            name='color_code',
            field=models.BooleanField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reports',
            name='operation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='parent_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reports',
            name='plan_fact',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reports',
            name='record_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reports',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reports',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
