# Generated by Django 5.1.7 on 2025-04-15 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "business_indicator",
            "0002_remove_reports_uploaded_by_alter_reports_color_code_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reports",
            new_name="Report",
        ),
    ]
