# Generated by Django 5.1.7 on 2025-04-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_indicator", "0003_rename_reports_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deviation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "managed": False,
            },
        ),
    ]
