# Generated by Django 5.1.7 on 2025-04-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_indicator", "0004_deviation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="show",
            field=models.CharField(
                choices=[("YES", "yes"), ("NO", "no")], default="NO", max_length=3
            ),
        ),
    ]
