# Generated by Django 5.1.7 on 2025-04-25 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0002_alter_business_responsible_person"),
        ("business_indicator", "0005_alter_report_show"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="business.business"
            ),
        ),
    ]
