"""
Django settings for bmt project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-sq+sj6_umg&nh8k_&zf*o37t-ed^&-fu2w2cvf9s%_ozssar_o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",  # before django.contrib.admin
    "unfold.contrib.filters",  # optional, if special filters are needed
    "unfold.contrib.forms",  # optional, if special form elements are needed
    "unfold.contrib.inlines",  # optional, if special inlines are needed
    "unfold.contrib.import_export",  # optional, if django-import-export package is used
    "unfold.contrib.guardian",  # optional, if django-guardian package is used
    "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'assignment',
    'business',
    'rest_framework',
    'business_indicator',
    "import_export",
    "mathfilters",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bmt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bmt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Celery settings
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'


#Email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'poghosyanmariam44@gmail.com'
EMAIL_HOST_PASSWORD = 'pkwm uqlp xalh qsbx'
DEFAULT_FROM_EMAIL = 'poghosyanmariam44@gmail.com'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static_files'  # Adjust 'static' if your CSS file is in a different folder
]

STATIC_ROOT = BASE_DIR / 'static'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

IMPORT_EXPORT_SKIP_ADMIN_LOG = True

UNFOLD = {
    "DASHBOARD_CALLBACK": "business_indicator.views.dashboard_callback",
}
# UNFOLD = {
# "SITE_TITLE": "Business monitoring administration",
#     "SITE_HEADER": "Business monitoring",
#     "SITE_URL": "/",
#     "SITE_ICON": lambda request: static("logos/soft.png"),
#     "SITE_FAVICONS": [
#         {
#             "rel": "icon",
#             "sizes": "256x256",
#             "type": "image/ico",
#             "href": lambda request: static("logos/favicon.ico"),
#         },
#     ],
#     "SHOW_HISTORY": True,
#     "SHOW_VIEW_ON_SITE": False,
#     "SHOW_BACK_BUTTON": True,
#     "SIDEBAR": {
#         "show_search": True,
#         "show_all_applications": True,
#         "navigation": [
#             {
#                 "separator": False,
#                 "collapsible": False,
#                 "items": [
#                     {
#                         "title": "Applications",
#                         "icon": "apps",
#                         "link": reverse_lazy("admin:index"),
#                         "permission": lambda request: request.user.is_staff,
#                     },
#                 ],
#             },
# {
#                 "title": "Applications",
#                 "separator": True,
#                 "collapsible": True,
#                 "items": [
#                     {
#                         "title": "Assignments",
#                         "icon": "assignment",
#                         "link": reverse_lazy("admin:assignments_assignment_changelist"),
#                         "permission": lambda request: request.user.is_staff,
#                     },
#                     {
#                         "title": "Assignments Title",
#                         "icon": "list_alt",
#                         "link": reverse_lazy("admin:assignments_assignmenttitle_changelist"),
#                         "permission": lambda request: request.user.is_staff,
#                     },
#                     {
#                         "title": "Reports",
#                         "icon": "chart_data",
#                         "link": reverse_lazy("admin:business_indicators_report_changelist"),
#                         "permission": lambda request: request.user.is_staff,
#                     },
#                     {
#                         "title": "Deviations",
#                         "icon": "monitoring",
#                         "link": reverse_lazy("admin:business_indicators_deviationhistory_changelist"),
#                         "permission": lambda request: request.user.is_staff,
#                     },
#                     {
#                         "title": "Businesses",
#                         "icon": "work",
#                         "link": reverse_lazy("admin:business_business_changelist"),
#                         "permission": lambda request: request.user.is_staff,
#                     },
#                 ],
#             },
#         ],
#     }
# }

