# Generated by Django 5.1.7 on 2025-04-11 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_business_alter_assignment_status_and_more'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business'),
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
